import type { Metadata } from "next";
import { Inter, GFS_Didot, } from "next/font/google";
import "./globals.css";
import ConvexClerkProvider from "@/providers/ConvexClerkProvider";
import { Toaster } from "@/components/ui/toaster"

const inter = Inter({ subsets: ["latin"] });
const didot = GFS_Didot({
  subsets: ['greek'],
  weight: ['400'],
  variable: '--font-didot'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/aion-logo-zip-file/favicon.png'
  }
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang='en'>
        <body className={`${inter.className} ${didot.variable}`}>
          <main>
            {children}
          </main>
          <Toaster />
        </body>
      </html>
    </ConvexClerkProvider>
  );
}

